name = "attempt-worker"
main = "src/index.ts"
compatibility_date = "2026-02-14"

[observability]
enabled = true

[observability.logs]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "api-worker"
database_id = "badf43da-5039-4326-8d0b-0185be98f761"

[[kv_namespaces]]
binding = "KV_HOT"
# Replaced by CI during deployment
id = "a6e1dde134824cb9931795ffa3a1b2d5"

[[durable_objects.bindings]]
name = "CHECKIN_SCHEDULER"
class_name = "CheckinScheduler"
script_name = "api-worker"
